### ISSUE TITLE
Minor typo and question

### ISSUE THREAD

**Issue by aarenson** [RTIInternational/conditional_api_trigger#9]
the very minorest of issues: typo in the README for the API Method, under How to use: requierd -> required.

If I were to use this EM to send an API call that required basic authentication, I'd guess that I'd include the  'Authorization: Basic ...' header in the API Header configuration. If you happen to have done that and know the exact syntax to use, I'd love to see it.

**Comment by dcleblond** [comment]
I'll make sure the next bugfix or feature update fixes the typo, thanks for pointing it out! 

I swear I thought I had used it with a basic authentication but I can't find an example. The one that I was thinking was actually "Api-Key: <<enter key here>>" I tried looking for a sample API that uses basic auth and couldn't find one. If I had one, I'd test and get the right syntax for ya. And if I find one, I'll update you!
